import { Point } from "./base/point.js";
import { Model } from "./base/model.js";
import { Cube } from "./base/cube.js";
import { Keyframe } from "./base/keyframe.js";
import { degToRad } from "../math/math.js";

let distalThumb = new Model("distalThumb");
distalThumb.setCubes([new Cube(25, 70, 25, new Point(-120, -65, 0))]);
distalThumb.completeModelUsingCubes();
distalThumb.setAnchor([-120, -30, 0]);
let distalThumbKeyFrame1 = new Keyframe(10);
distalThumbKeyFrame1.setRotation([degToRad(-40), 0, 0]);
distalThumb.addAnimation(distalThumbKeyFrame1);
let distalThumbKeyFrame2 = new Keyframe(20);
distalThumbKeyFrame2.setRotation([0, 0, 0]);
distalThumb.addAnimation(distalThumbKeyFrame2);

let distalIndex = new Model("distalIndex");
distalIndex.setCubes([new Cube(20, 50, 20, new Point(-72, -295, 0))]);
distalIndex.completeModelUsingCubes();
distalIndex.setAnchor([-72, -270, 0]);
let distalIndexKeyFrame1 = new Keyframe(10);
distalIndexKeyFrame1.setRotation([degToRad(-40), 0, 0]);
distalIndex.addAnimation(distalIndexKeyFrame1);
let distalIndexKeyFrame2 = new Keyframe(20);
distalIndexKeyFrame2.setRotation([0, 0, 0]);
distalIndex.addAnimation(distalIndexKeyFrame2);

let distalMiddle = new Model("distalMiddle");
distalMiddle.setCubes([new Cube(20, 50, 20, new Point(-24, -295, 0))]);
distalMiddle.completeModelUsingCubes();
distalMiddle.setAnchor([-24, -270, 0]);
let distalMiddleKeyFrame1 = new Keyframe(10);
distalMiddleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
distalMiddle.addAnimation(distalMiddleKeyFrame1);
let distalMiddleKeyFrame2 = new Keyframe(20);
distalMiddleKeyFrame2.setRotation([0, 0, 0]);
distalMiddle.addAnimation(distalMiddleKeyFrame2);

let distalRing = new Model("distalRing");
distalRing.setCubes([new Cube(20, 50, 20, new Point(24, -295, 0))]);
distalRing.completeModelUsingCubes();
distalRing.setAnchor([24, -270, 0]);
let distalRingKeyFrame1 = new Keyframe(10);
distalRingKeyFrame1.setRotation([degToRad(-40), 0, 0]);
distalRing.addAnimation(distalRingKeyFrame1);
let distalRingKeyFrame2 = new Keyframe(20);
distalRingKeyFrame2.setRotation([0, 0, 0]);
distalRing.addAnimation(distalRingKeyFrame2);

let distalLittle = new Model("distalLittle");
distalLittle.setCubes([new Cube(20, 50, 20, new Point(72, -295, 0))]);
distalLittle.completeModelUsingCubes();
distalLittle.setAnchor([72, -270, 0]);
let distalLittleKeyFrame1 = new Keyframe(10);
distalLittleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
distalLittle.addAnimation(distalLittleKeyFrame1);
let distalLittleKeyFrame2 = new Keyframe(20);
distalLittleKeyFrame2.setRotation([0, 0, 0]);
distalLittle.addAnimation(distalLittleKeyFrame2);

let intermediateIndex = new Model("intermediateIndex");
intermediateIndex.setCubes([new Cube(30, 70, 30, new Point(-72, -235, 0))]);
intermediateIndex.completeModelUsingCubes();
intermediateIndex.setAnchor([-72, -200, 0]);
intermediateIndex.addChildren("distalIndex", distalIndex);
intermediateIndex.updateModelBeingDrawnFully();
let intermediateIndexKeyFrame1 = new Keyframe(10);
intermediateIndexKeyFrame1.setRotation([degToRad(-40), 0, 0]);
intermediateIndex.addAnimation(intermediateIndexKeyFrame1);
let intermediateIndexKeyFrame2 = new Keyframe(20);
intermediateIndexKeyFrame2.setRotation([0, 0, 0]);
intermediateIndex.addAnimation(intermediateIndexKeyFrame2);

let intermediateMiddle = new Model("intermediateMiddle");
intermediateMiddle.setCubes([new Cube(30, 70, 30, new Point(-24, -235, 0))]);
intermediateMiddle.completeModelUsingCubes();
intermediateMiddle.setAnchor([-24, -200, 0]);
intermediateMiddle.addChildren("distalMiddle", distalMiddle);
intermediateMiddle.updateModelBeingDrawnFully();
let intermediateMiddleKeyFrame1 = new Keyframe(10);
intermediateMiddleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
intermediateMiddle.addAnimation(intermediateMiddleKeyFrame1);
let intermediateMiddleKeyFrame2 = new Keyframe(20);
intermediateMiddleKeyFrame2.setRotation([0, 0, 0]);
intermediateMiddle.addAnimation(intermediateMiddleKeyFrame2);

let intermediateRing = new Model("intermediateRing");
intermediateRing.setCubes([new Cube(30, 70, 30, new Point(24, -235, 0))]);
intermediateRing.completeModelUsingCubes();
intermediateRing.setAnchor([24, -200, 0]);
intermediateRing.addChildren("distalRing", distalRing);
intermediateRing.updateModelBeingDrawnFully();
let intermediateRingKeyFrame1 = new Keyframe(10);
intermediateRingKeyFrame1.setRotation([degToRad(-40), 0, 0]);
intermediateRing.addAnimation(intermediateRingKeyFrame1);
let intermediateRingKeyFrame2 = new Keyframe(20);
intermediateRingKeyFrame2.setRotation([0, 0, 0]);
intermediateRing.addAnimation(intermediateRingKeyFrame2);

let intermediateLittle = new Model("intermediateLittle");
intermediateLittle.setCubes([new Cube(30, 70, 30, new Point(72, -235, 0))]);
intermediateLittle.completeModelUsingCubes();
intermediateLittle.setAnchor([72, -200, 0]);
intermediateLittle.addChildren("distalLittle", distalLittle);
intermediateLittle.updateModelBeingDrawnFully();
let intermediateLittleKeyFrame1 = new Keyframe(10);
intermediateLittleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
intermediateLittle.addAnimation(intermediateLittleKeyFrame1);
let intermediateLittleKeyFrame2 = new Keyframe(20);
intermediateLittleKeyFrame2.setRotation([0, 0, 0]);
intermediateLittle.addAnimation(intermediateLittleKeyFrame2);

let proximalThumb = new Model("proximalThumb");
proximalThumb.setCubes([new Cube(40, 100, 40, new Point(-120, 20, 0))]);
proximalThumb.completeModelUsingCubes();
proximalThumb.setAnchor([-100, 70, 0]);
proximalThumb.addChildren("distalThumb", distalThumb);
proximalThumb.updateModelBeingDrawnFully();
let proximalThumbKeyFrame1 = new Keyframe(10);
proximalThumbKeyFrame1.setRotation([degToRad(-40), 0, 0]);
proximalThumb.addAnimation(proximalThumbKeyFrame1);
let proximalThumbKeyFrame2 = new Keyframe(20);
proximalThumbKeyFrame2.setRotation([0, 0, 0]);
proximalThumb.addAnimation(proximalThumbKeyFrame2);

let proximalIndex = new Model("proximalIndex");
proximalIndex.setCubes([new Cube(40, 100, 40, new Point(-72, -150, 0))]);
proximalIndex.completeModelUsingCubes();
proximalIndex.setAnchor([-72, -100, 0]);
proximalIndex.addChildren("intermediateIndex", intermediateIndex);
proximalIndex.updateModelBeingDrawnFully();
let proximalIndexKeyFrame1 = new Keyframe(10);
proximalIndexKeyFrame1.setRotation([degToRad(-40), 0, 0]);
proximalIndex.addAnimation(proximalIndexKeyFrame1);
let proximalIndexKeyFrame2 = new Keyframe(20);
proximalIndexKeyFrame2.setRotation([0, 0, 0]);
proximalIndex.addAnimation(proximalIndexKeyFrame2);

let proximalMiddle = new Model("proximalMiddle");
proximalMiddle.setCubes([new Cube(40, 100, 40, new Point(-24, -150, 0))]);
proximalMiddle.completeModelUsingCubes();
proximalMiddle.setAnchor([-24, -100, 0]);
proximalMiddle.addChildren("intermediateMiddle", intermediateMiddle);
proximalMiddle.updateModelBeingDrawnFully();
let proximalMiddleKeyFrame1 = new Keyframe(10);
proximalMiddleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
proximalMiddle.addAnimation(proximalMiddleKeyFrame1);
let proximalMiddleKeyFrame2 = new Keyframe(20);
proximalMiddleKeyFrame2.setRotation([0, 0, 0]);
proximalMiddle.addAnimation(proximalMiddleKeyFrame2);

let proximalRing = new Model("proximalRing");
proximalRing.setCubes([new Cube(40, 100, 40, new Point(24, -150, 0))]);
proximalRing.completeModelUsingCubes();
proximalRing.setAnchor([24, -100, 0]);
proximalRing.addChildren("intermediateRing", intermediateRing);
proximalRing.updateModelBeingDrawnFully();
let proximalRingKeyFrame1 = new Keyframe(10);
proximalRingKeyFrame1.setRotation([degToRad(-40), 0, 0]);
proximalRing.addAnimation(proximalRingKeyFrame1);
let proximalRingKeyFrame2 = new Keyframe(20);
proximalRingKeyFrame2.setRotation([0, 0, 0]);
proximalRing.addAnimation(proximalRingKeyFrame2);

let proximalLittle = new Model("proximalLittle");
proximalLittle.setCubes([new Cube(40, 100, 40, new Point(72, -150, 0))]);
proximalLittle.completeModelUsingCubes();
proximalLittle.setAnchor([72, -100, 0]);
proximalLittle.addChildren("intermediateLittle", intermediateLittle);
proximalLittle.updateModelBeingDrawnFully();
let proximalLittleKeyFrame1 = new Keyframe(10);
proximalLittleKeyFrame1.setRotation([degToRad(-40), 0, 0]);
proximalLittle.addAnimation(proximalLittleKeyFrame1);
let proximalLittleKeyFrame2 = new Keyframe(20);
proximalLittleKeyFrame2.setRotation([0, 0, 0]);
proximalLittle.addAnimation(proximalLittleKeyFrame2);

let hand = new Model("hand");
hand.setCubes([new Cube(200, 200, 50, new Point(0, 0, 0))]);
hand.completeModelUsingCubes();
hand.setAnchor([0, 100, 0]);
hand.addChildren("proximalThumb", proximalThumb);
hand.updateModelBeingDrawnFully();
hand.addChildren("proximalIndex", proximalIndex);
hand.updateModelBeingDrawnFully();
hand.addChildren("proximalMiddle", proximalMiddle);
hand.updateModelBeingDrawnFully();
hand.addChildren("proximalRing", proximalRing);
hand.updateModelBeingDrawnFully();
hand.addChildren("proximalLittle", proximalLittle);
hand.updateModelBeingDrawnFully();

export { hand };
